### PR TITLE
Update tauri.studio links in Vite config

### PR DESCRIPTION
**Pull request by olivierlemasle**
Update tauri.studio links to tauri.app in Vite configuration comments.

This was left over in #75.

### What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Docs
- [ ] New Binding issue #___
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

### Does this PR introduce a breaking change?

- [ ] Yes, and the changes were approved in issue #___
- [x] No

### Checklist
- [ ] When resolving issues, they are referenced in the PR's title (e.g `fix: remove a typo, closes #___, #___`)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/create-tauri-app/blob/dev/.changes/readme.md).
- [x] I have added a convincing reason for adding this feature, if necessary

### CODE REVIEW

**Review by amrbashir — APPROVED** [review]
Thanks

**Comment by olivierlemasle** [comment]
Thanks for the merge.
@amrbashir Out of curiosity, and to learn the right process here, why did you **remove** the changefile for this PR, when you **added** it last year in #75, which is the same kind of change?

**Comment by amrbashir** [comment]
to be honest, I don't remember, maybe we needed to release a new version at the time but currently it is not urgent since it will redirect to the correct website anyways, or maybe because I used to add a change file for anything but right now I have been only adding change files for the user-facing changes only and when it feels necessary.

**Comment by olivierlemasle** [comment]
Ok, thanks for the reply!

**Pull request merged**
